version: '3.3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"


  fast_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/API
